version: '3'

services:
  web:
    build: .
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:shop_app --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web


